<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQgj4VXx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQgj4VXx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQgj4VXx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQgj4VXx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQgj4VXx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Qgj4VXx',
    'container.build_id' => 'd40b027a',
    'container.build_time' => 1536431828,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQgj4VXx');
